{% set year = "2018" %}
{% set cycle = "2" %}
{% set version ="0" %}

package:
  name: 08-id-iss-analysis
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 1

requirements:
  run:
    - isstools
    - numexpr
    - netcdf4
    - xraylarch
